pipeline:
  identifier: Build_shiftleft_java_demo_1696269431280
  name: Build and Test
  orgIdentifier: default
  projectIdentifier: HARQwietjava
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1695829315182
        repoName: shiftleft-java-demo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: SL Analyze
                  identifier: SL_Analyze
                  spec:
                    connectorRef: DOCQwietjava
                    image: shiftleft/core:latest
                    shell: Sh
                    command: sl analyze --app HAR-Qwiet-java
                    envVariables:
                      SHIFTLEFT_ACCESS_TOKEN: <+secrets.getValue("Qwiet_Token")>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
  tags: {}
