pipeline:
  identifier: Build_shiftleft_java_demo_1696264268222
  name: Build shiftleft-java-demo
  orgIdentifier: default
  projectIdentifier: HARQwietjava
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1695829315182
        repoName: shiftleft-java-demo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Qwiet Analysis
                  identifier: Qwiet_Analysis
                  spec:
                    connectorRef: account.harnessImage
                    image: shiftleft/core:latest
                    shell: Sh
                    command: sl analyze --app HAR-Qwiet-java
                    envVariables:
                      SHIFTLEFT_ACCESS_TOKEN: <+secrets.getValue("SHIFTLEFT_ACCESS_TOKEN")>
                  description: Using Qwiet AI's preZero platform
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
